import moment from "moment";
import Button from "material-ui/Button";

import { Divider } from "../../common/FormSection";
import RoleSection from "./Role";
import TokensSection from "./Tokens";
import MarginAmountsSection from "./MarginAmounts";
import ExpirationSection from "./Expiration";
import RelayExchangeSection from "./RelayExchange";

export default class GenerateOrder extends React.Component {
  state = {
    role: `lender`,

    // token addresses
    lendTokenAddress: `WETH_SM_ADDRESS_HERE`,
    interestTokenAddress: `ZRX_SM_ADDRESS_HERE`,
    marginTokenAddress: `MKR_SM_ADDRESS_HERE`,

    // token amounts
    lendTokenAmount: 40,
    interestAmount: 41,

    // margin amounts
    initialMarginAmount: 42,
    liquidationMarginAmount: 43,

    // expiration date/time
    expirationDate: moment(),

    // relay/exchange settings
    sendToRelayExchange: false,
    feeRecipientAddress: `address_here`,
    lenderRelayFee: 44,
    traderRelayFee: 45
  };

  setStateFor = key => value => this.setState({ [key]: value });

  setStateForInput = key => event =>
    this.setState({ [key]: event.target.value });

  setRole = (e, value) => this.setState({ role: value });

  setRelayCheckbox = (e, value) =>
    this.setState({ sendToRelayExchange: value });

  render() {
    return (
      <div>
        <RoleSection role={this.state.role} setRole={this.setRole} />

        <Divider />

        <TokensSection
          role={this.state.role}
          // state setters
          setStateForAddress={this.setStateFor}
          setStateForInput={this.setStateForInput}
          // address states
          lendTokenAddress={this.state.lendTokenAddress}
          interestTokenAddress={this.state.interestTokenAddress}
          marginTokenAddress={this.state.marginTokenAddress}
          // token amounts
          lendTokenAmount={this.state.lendTokenAmount}
          interestAmount={this.state.interestAmount}
        />

        <Divider />

        <MarginAmountsSection
          setStateForInput={this.setStateForInput}
          initialMarginAmount={this.state.initialMarginAmount}
          liquidationMarginAmount={this.state.liquidationMarginAmount}
        />

        <Divider />

        <ExpirationSection
          setExpirationDate={this.setStateFor(`expirationDate`)}
          expirationDate={this.state.expirationDate}
        />

        <Divider />

        <RelayExchangeSection
          // state setters
          setStateForInput={this.setStateForInput}
          setRelayCheckbox={this.setRelayCheckbox}
          // form states
          sendToRelayExchange={this.state.sendToRelayExchange}
          feeRecipientAddress={this.state.feeRecipientAddress}
          lenderRelayFee={this.state.lenderRelayFee}
          traderRelayFee={this.state.traderRelayFee}
        />

        <Divider />

        <Button raised color="primary">
          Sign Order
        </Button>
      </div>
    );
  }
}

// TODO - all visible params are required to submit the form
// TODO - on submit, translate datetime to epoch time: expirationUnixTimestampSec

// Hashing TODOs
// ===
// TODO - generate salt with generatePseudoRandomSalt() from b0x_tester.js
// TODO - include salt in the hash

// - the "submit" of this form is "Sign Order". this signs the order with the maker's private key and generartes a json object with the
//   - sign order w/ maker's private key
//   - generates JSON w/ above params + the maker's ECDSA signigure params (generated by the sign function)
// - to generate the "hash" use the getLendOrderHashHex function is b0x.js.
