const BZx = require("./../contracts/test_network/deployed/BZx");
const BZxVault = require("./../contracts/test_network/deployed/BZxVault");
const TestToken0 = require("./../contracts/test_network/deployed/TestToken0");
const TestToken1 = require("./../contracts/test_network/deployed/TestToken1");
const TestToken2 = require("./../contracts/test_network/deployed/TestToken2");
const TestToken3 = require("./../contracts/test_network/deployed/TestToken3");
const TestToken4 = require("./../contracts/test_network/deployed/TestToken4");
const WETH = require("./../contracts/test_network/deployed/WETH");
const ZeroExV2Helper = require("./../contracts/test_network/build_contracts/ZeroExV2Helper");

module.exports.zeroExV2Helper = ZeroExV2Helper;
module.exports.bZx = BZx;
module.exports.bZxVault = BZxVault;
module.exports.testToken0 = TestToken0;
module.exports.testToken1 = TestToken1;
module.exports.testToken2 = TestToken2;
module.exports.testToken3 = TestToken3;
module.exports.testToken4 = TestToken4;
module.exports.weth = WETH;
